### ISSUE TITLE
error while executing docking.toml

### ISSUE THREAD

**Issue by aniketmoha9** [haddocking/haddock3#101]
File "/home/eigenket/haddock3/src/haddock/modules/refinement/flexref/__init__.py", line 79, in run
    first_model = models_to_refine[0]
IndexError: list index out of range

**Comment by joaomcteixeira** [comment]
@aniketmoha9 thanks for reporting. I will look at it today and come back to you asap. Likely that issue is already solved in the pending PRs. I appreciate any additional information on the running setup that you could share with us. Can you share the configuration file without revealing the input PDBs you are using, since that is private information of yours. Thanks.

**Comment by aniketmoha9** [comment]
thanks for replying. I am currently running the examples which is given in haddock3 examples folder

**Comment by joaomcteixeira** [comment]
Note the current `main` branch is heavily under development. Any feedback you can provide will be very welcomed. Also, the "stable" haddock3 version is in branch `alpha1`, if you want to give it a try and compare.

**Comment by aniketmoha9** [comment]
when i downloaded the alpha2 version. and ran a simulation.
i got these output messages
+ FCC clustering with cutoff: 0.60 and max size: 4

+ FASTCONTACT not correctly configured in haddock3.ini

+ DFIRE not correctly configured in haddock3.ini

+ DockQ not correctly configured in haddock3.ini

+ Saving single-structure analysis

+ Saving cluster analysis

**Comment by aniketmoha9** [comment]
> Note the current `main` branch is heavily under development. Any feedback you can provide will be very welcomed. Also, the "stable" haddock3 version is in branch `alpha1`, if you want to give it a try and compare.

alpha1 is running. I want to specify the binding region, how can i specify that and which file needs to be edited?

**Comment by aniketmoha9** [comment]
Thank you for the response, but we want a way by which we can create ambig.tbl file locally without using any web servers.

**Comment by joaomcteixeira** [comment]
Hi @aniketmoha9 

Sorry for such a delay in replying to you properly. Coming back to your first question, I believe your error is because the `clustfcc` and `seletopclusts` is activated. The `clustfcc` is curretly experimental and pending solution from our side (https://github.com/haddocking/fcc/pull/10). Please deactivate those two modules to run the `docking` example. We will keep you posted when the FCC is fully incorporated.

**Comment by aniketmoha9** [comment]
+ ERROR: Job rigid_body/complex_it0_000000.inp has failed, please check the output rigid_body/complex_it0_000000.out
 i am getting this error while running the run_haddock.py script in haddock alpha 1 version

**Comment by joaomcteixeira** [comment]
Hi,
we definitively need to integrate the `clustfcc` so you can jump straight to the `main` branch here :relaxed: . If you don't need the `clustfcc` right now, you could already try the new version in `main`. We are currently working on setting the benchmark for HADDOCK3. ASAP that is finished we will address the `clustfcc` issue. Cheers!
