### ISSUE TITLE
Add option to "sortby" in `caprieval`

### ISSUE THREAD

**Issue by rvhonorato** [haddocking/haddock3#153]
We could sort the output of `caprieval` by `score` or some of the calculated metrics.

**Comment by joaomcteixeira** [comment]
Since you are refering this. I would suggest also to arrange the file not by tab separated columns but by fixed number of spaces, so that columns are always well aligned (by giving enough free spaces.

**Comment by amjjbonvin** [comment]
And while at it why not also directly include in the output the Haddock score?

**Comment by rvhonorato** [comment]
I think that having the score there would be valuable for a few type of analysis, **but** this is out of scope for a module that calculates the CAPRI metrics since the score is not part of it. 

What sort of analysis could be done with the capri metrics + scores? Ideally this should be a different module.

Anyway this is my opinion, we can of course add it, rule # 1 😉

**Comment by amjjbonvin** [comment]
For optimisation purposes you want to know how the various CAPRI metrics relate to the score…
Also to simply look at the scores in a human readable format and check the models

E.g. we use it on the server to generate plots. So since it is already there anyway, it is a small thing to add the score as an additional column (and even the components of the score if they are part of the json file

**Comment by rvhonorato** [comment]
Reopened since we should not use pandas as a dependency and this option needs to be re-implemented.

**Comment by rvhonorato** [comment]
Reverted with #184
