### ISSUE TITLE
Create a flexible benchmark scenario loader

### ISSUE THREAD

**Issue by rvhonorato** [haddocking/haddock3#194]
Now the benchmarking scenarios are hardcoded in `cli_bm`, we should have a more flexible way of defining such scenarios.

**Comment by joaomcteixeira** [comment]
> https://github.com/haddocking/haddock3/pull/195#pullrequestreview-831363521

I thought a lot about where to put the configuration templates when I designed the CLI. You are right to say that haven the templates inside the CLI might not be the best. But I am not sure if it is best/feasible having them outside functions (for example plain text files). However, we could have the template scenario configs in a module outside the CLI so that the client can import them. But I trust they should be functions that return a formatted string. That's pretty flexible and easy to document with the docstring.

**Comment by rvhonorato** [comment]
Addressed with https://github.com/haddocking/haddock-runner
