### ISSUE TITLE
`libhpc` broken after exporting environment variables to a file per module 

### ISSUE THREAD

**Issue by rvhonorato** [haddocking/haddock3#225]
Introduced with #214

**Comment by joaomcteixeira** [comment]
Yeah, I forgot to update that.
[here: https://github.com/haddocking/haddock3/blob/94657cadd69b71ac4afe074c126e644c83c9eb81/src/haddock/libs/libhpc.py#L75
](https://github.com/haddocking/haddock3/blob/94657cadd69b71ac4afe074c126e644c83c9eb81/src/haddock/libs/libhpc.py#L55-L62)

instead of taking from `tasks[0]` take from `tasks[0].envvars['variable']`
