### ISSUE TITLE
What is order in HaddockModule?

### ISSUE THREAD

**Issue by Atakanzsn** [haddocking/haddock3#544]
Hi, I am trying to run HaddockModule from mdscoring folder but I didn't understand what is 'order' parameter in HaddockModule. Can anyone help me?

**Comment by amjjbonvin** [comment]
Did you try one of the examples first?

**Comment by joaomcteixeira** [comment]
Hi @Atakanzsn 
Please note that using HADDOCK3 as a pure python library is not yet fully developed. Having said this, the `order` parameter is used by the workflow manager to understand which step the module belongs. For example, the first module in the workflow will have `order = 0`. If you can try to give the `order` equals to the number of the step folder you are in. Otherwise, if you are using the `mdscoring` module as a stand-alone you can give `order=0`.

**Comment by Atakanzsn** [comment]
Hi, thanks for your answers. I just realized that haddock is not compatible with windows, so I'm going to install wsl and try again. For now, I'm closing the issue.
