### ISSUE TITLE
HADDOCK3 lost the support for PDB-specific restraint files

### ISSUE THREAD

**Issue by amjjbonvin** [haddocking/haddock3#557]
In HADDOCK2.4, we can provide manually restraints files specific for each model to be calculated in it0. This requires putting the `ambig.tbl_XXX` files manually into the `structures/it0` directory (where XXX is the model number).

This mechanism is used by the server in case more than 50% random removal is turned on.

In HADDOCK3, although the CNS machinery does support it, we have no way to do it. I guess we don't want to specify in the cfg file e.g. 10000 such files. And when restarting a specific stage the directory is deleted, i.e. there is no way to manually copy the files into the specific directory...

We should think of a way of supporting this.  May-be providing the files as a tar archive (`ambig.tbl.tgz`) and in that case the python machinery should copy it to the proper directory and unpack it.

And there is more to it, as in HADDOCK2.4, the files are then copied to the next stage (it1), making sure the correct file is copied since there is a model renumbering happening between it0 and it1, which must also be the case in haddock3.

**Comment by mgiulini** [comment]
Interesting and very necessary feature! It would make things much easier when testing arctic3d for example. A few questions on the desired features:

- I like the idea of the tar archive. The alternative could be a regular expression (such as `ambig.tbl_*`) but the .tar sounds better. We could create an `ambig_archive` parameter (similar to `ambig_fname`)
- what is the expected behavior if sampling = 100 and there are 5 tbl files? what about the other way around (5 vs 100)? I guess that in the first case we should evenly partition the models, while in the second we should stick to the first tbl files and raise a warning
- we can create a new model attribute `tbl_file` to be associated to each model at the beginning of the run. When `ambig_archive` is defined and `model.tbl_file != None` we should be able to easily assign each restraint file to the model to be refined
- what is the expected behavior if the user defines an `ambig_archive` in rigidbody and an `ambig_fname` later on? the latter should overwrite any previous restraint information, correct?
- do we want to put a threshold on the maximum number of files contained in the archive? 10K?

**Comment by amjjbonvin** [comment]
> what is the expected behavior if sampling = 100 and there are 5 tbl files? what about the other way around (5 vs 100)? I guess that in the first case we should evenly partition the models, while in the second we should stick to the first tbl files and raise a warning
The CNS scripts only check if the `ambig.tbl_XXX` file exists (where XXX is the model number), it not it read the default ambig.tbl.
So those files should be present for each model (or a default ambig.tbl file should be present).
> what is the expected behavior if the user defines an ambig_archive in rigidbody and an ambig_fname later on? the latter should overwrite any previous restraint information, correct?
This was not possible in the past, now it would be possible (but could lead to weird behaviour). But indeed in such a case it should overwrite any previous info. 
But if not defined later on, we should have a way to tell the module to use the previous set of restraint (ideally it should copy and renumber the files to match the model numbering of the new stage)
> do we want to put a threshold on the maximum number of files contained in the archive? 10K?
It should match the number of models defined by the sampling parameters (or should have the same limit as the max number of models generated).
