### ISSUE TITLE
Process slurm TIMEOUT not handeled in hpc mode

### ISSUE THREAD

**Issue by VGPReys** [haddocking/haddock3#718]
**Describe the bug**
`KeyError` obtained during a `mdref` run that seems to take too much time.

```
[2023-10-11 07:04:37,583 libhpc INFO] >> Waiting... (60.00s)
[2023-10-11 07:05:40,695 libutil ERROR] 'TIMEOUT'
Traceback (most recent call last):
  File "/trinity/login/vreys/benchmarking/haddock3/src/haddock/libs/libutil.py", line 310, in log_error_and_exit
    yield
  File "/trinity/login/vreys/benchmarking/haddock3/src/haddock/clis/cli.py", line 178, in main
    workflow.run()
  File "/trinity/login/vreys/benchmarking/haddock3/src/haddock/libs/libworkflow.py", line 39, in run
    step.execute()
  File "/trinity/login/vreys/benchmarking/haddock3/src/haddock/libs/libworkflow.py", line 143, in execute
    self.module.run()
  File "/trinity/login/vreys/benchmarking/haddock3/src/haddock/modules/base_cns_module.py", line 59, in run
    self._run()
  File "/trinity/login/vreys/benchmarking/haddock3/src/haddock/modules/refinement/mdref/__init__.py", line 113, in _run
    engine.run()
  File "/trinity/login/vreys/benchmarking/haddock3/src/haddock/libs/libhpc.py", line 183, in run
    worker.update_status()
  File "/trinity/login/vreys/benchmarking/haddock3/src/haddock/libs/libhpc.py", line 113, in update_status
    self.job_status = JOB_STATUS_DIC[status]
KeyError: 'TIMEOUT'
[2023-10-11 07:05:40,701 libutil ERROR] 'TIMEOUT'
[2023-10-11 07:05:40,701 libutil ERROR] An error has occurred, see log file. And contact the developers if needed.
```

**To Reproduce**
```toml
clean = true
ncores = 2
mode = "hpc"
queue = "short"
queue_limit = 400
concat = 5
run_dir = "run1"
molecules = [
    "../data/1HE8_r_u.pdb",
    "../data/1HE8_l_u.pdb",
]

[topoaa]
autohis = true
[rigidbody]
unambig_fname = "../data/1HE8_restraint-bodies.tbl"
hbond_fname = "../data/1HE8_hbonds.tbl"
ligand_param_fname = "../data/1HE8_ligand.param"
ligand_top_fname = "../data/1HE8_ligand.top"
tolerance = 5
sampling = 10000
ranair = true
[caprieval]
reference_fname = "../data/1HE8_target.pdb"
[seletop]
select = 400
['caprieval.1']
reference_fname = "../data/1HE8_target.pdb"
[flexref]
unambig_fname = "../data/1HE8_restraint-bodies.tbl"
hbond_fname = "../data/1HE8_hbonds.tbl"
ligand_param_fname = "../data/1HE8_ligand.param"
ligand_top_fname = "../data/1HE8_ligand.top"
tolerance = 5
contactairs = true
['caprieval.2']
reference_fname = "../data/1HE8_target.pdb"
[mdref]
hbond_fname = "../data/1HE8_hbonds.tbl"
ligand_param_fname = "../data/1HE8_ligand.param"
ligand_top_fname = "../data/1HE8_ligand.top"
tolerance = 5
contactairs = true
unambig_fname = "../data/1HE8_restraint-bodies.tbl"
['caprieval.3']
reference_fname = "../data/1HE8_target.pdb"
[clustfcc]
threshold = 4
[seletopclusts]
top_models = 4
['caprieval.4']
reference_fname = "../data/1HE8_target.pdb"
```

**Expected behavior**
I guess in case of timeout, the process should be restarted ?

**Comment by rvhonorato** [comment]
Not a bug, this behaviour is not accounted for therefore it should be an enhancement

**Comment by rvhonorato** [comment]
Resubmitting is not a solution because it does not guarantee that the job will finish and will eventually create the need to babysit the process. 

Instead what should be done is that the cluster in which these long runs will be submitted should have a dedicated partition without an infinite time limit.

**Comment by amjjbonvin** [comment]
> Instead what should be done is that the cluster in which these long runs will be submitted should have a dedicated partition without an infinite time limit.
> 
That is a rather dangerous solutions since you might end with nothing running (or running for ever) since there are many reason a job is failing in the queue. Can’t those failure be simply accepted as part of the tolerated failed jobs (the tolerance parameter)?

Or is this related to the openMM module which might take much longer? 
If you want to run very long openMM jobs, you need to match the queue limits. 
Might be good for that to have an option to extend a previous openMM run, i.e. cutting the MD part into multiple modules to match the queue limitations (no HPC center will give you infinite queues)

**Comment by rvhonorato** [comment]
> That is a rather dangerous solutions since you might end with nothing running (or running for ever) since there are many reason a job is failing in the queue. 

Then we need to make sure things don't run forever, instead of just patching up the behaviour with hot-fixes which will definitively creep up and start stacking babysitting monitoring (same pattern as the 2+ series).

I don't know what this is about specifically, so thinking in general terms - we have a custom SLURM wrapper that interfaces the haddock workflow execution layer with the queue scheduler. 

One option is to keep adding fault tolerancy to the wrapper (as this issue suggests), another is to make sure you know what you are doing when you are using an HPC, such as properly setting up the partition to be used and another yet for code quality that does not allow for indefinite consumption of resources (think of price/energy consumption here).

**Comment by VGPReys** [comment]
> Or is this related to the openMM module which might take much longer? If you want to run very long openMM jobs, you need to match the queue limits. Might be good for that to have an option to extend a previous openMM run, i.e. cutting the MD part into multiple modules to match the queue limitations (no HPC center will give you infinite queues).

I obtained a TIMEOUT during a `mdref` run.

**Comment by mgiulini** [comment]
> 
> > Can’t those failure be simply accepted as part of the tolerated failed jobs (the tolerance parameter)?
> 
> I can map the TIMEOUT status to a `failure` one if you think this is a better solution.

This sounds like a good solution! it's nice to handle this job status, but it's easier to label the corresponding job as failed.
