### ISSUE TITLE
Using Haddock commercially

### ISSUE THREAD

**Issue by YoelShoshan** [haddocking/haddock3#742]
Hi!
I can see that there's a hard dependency on CNS
https://github.com/haddocking/haddock3/issues/82
and its license does not seem to support commercial usage.

What is the recommended process for a anyone who wants to use Haddock commercially, assuming that running it on a remote server is not an option (only locally) ?

**Comment by amjjbonvin** [comment]
In order to run HADDOCK for commercial use  you will indeed need a CNS license.

Biovia which is handling those licenses ( https://www.3ds.com/how-to-buy/contact-sales/), even if officially they don’t distribute CNS anymore.
This should entitle you to use the non-profit version of CNS since Biovia does not really supports CNS (or rather CNX as they used to call it).
A contact person at Biovia who is aware of HADDOCK and CNS is Steve Vallis - ***@***.*** ***@***.***>
If you need support in running haddock3, this should be arranged via a consulting contract via Utrecht University.
Contact me (Alexandre Bonvin) for my info if needed.

**Comment by YoelShoshan** [comment]
@amjjbonvin thanks!
